# -*- coding: utf-8 -*-
"""Online Exam Monitioring 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEctgp-ZpTL4VXEG_wNlmF2cvZZPp7Nb
"""

time_interval = 5

FACE_VIOLATION_TIME = 15
TAB_INACTIVE_TIME = 10
WINDOW_CONTINUOUS_TIME = 15

face_required_logs = FACE_VIOLATION_TIME // time_interval
tab_required_logs = TAB_INACTIVE_TIME // time_interval
window_required_logs = WINDOW_CONTINUOUS_TIME // time_interval


input_dataset = [
    ('time1', True,  True, 0, True, True),
    ('time2', False, True, 1, False, True),
    ('time3', True, False, 1, True, True),
    ('time4', True, False, 0, True, True),
    ('time5', True, False, 0, False, True),
    ('time6',True, False, 0, False, True),
]


risk_score = 0
violations = []

face_absent_count = 0
window_continuous_count = 0
tab_inactive_count = 0
multiple_face_flag = False




for log in input_dataset :
    timestamp, face_detected, multiple_faces, window_switch, audio_detected, exam_tab_active = log


    if not face_detected:
        face_absent_count = face_absent_count + 1
        if face_absent_count == face_required_logs:
            risk_score = risk_score + 10
            violations.append(f"Face not detected for {FACE_VIOLATION_TIME} seconds")
    else:
        face_absent_count = 0

    # Rule 2: Multiple faces
    if multiple_faces and not multiple_face_flag:
        risk_score = risk_score + 20
        violations.append("Multiple faces detected")
        multiple_face_flag = True

    # Rule 3A: Window switch > 2
    if window_switch > 2:
        risk_score = risk_score + 5
        violations.append("Window switch count greater than 2")

    # Rule 3B: Continuous switching for defined seconds
    if window_switch > 0:
        window_continuous_count = window_continuous_count + 1
        if window_continuous_count == window_required_logs:
            risk_score =  risk_score + 10
            violations.append(f"Continuous window switching for {WINDOW_CONTINUOUS_TIME} seconds")
    else:
        window_continuous_count = 0

    # Rule 4: Audio detected
    if audio_detected:
        risk_score = risk_score + 5
        violations.append("Audio detected")

    # Rule 5: Tab inactive for defined seconds
    if not exam_tab_active:
        tab_inactive_count = tab_inactive_count + 1
        if tab_inactive_count == tab_required_logs:
            risk_score = risk_score + 10
            violations.append(f"Exam tab inactive for {TAB_INACTIVE_TIME} seconds")
    else:
        tab_inactive_count = 0


if risk_score <= 10:
    status = "NORMAL"
elif risk_score <= 25:
    status = "WARNING"
else:
    status = "CRITICAL"

print("Total Risk Score:", risk_score)
print("Final Status:", status)
print("Violations Found:")
for v in violations:
    print("-", v)