# -*- coding: utf-8 -*-
"""online exam monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvt-IYsY1CsICstTZNpG03zf6aI6lFmX
"""

input_dataset = [
    ('time1',True,False,0,False,True),
    ('time2',True,True,0,False,True),
    ('time3',True,False,1,False,True),
    ('time4',True,False,0,True,True),
    ('time5',True,False,0,False,True),
    ('time6',True,False,3,True,True),
]



risk_score = 0
violations = []

no_face_datected_count = 0
window_switch_continuous = 0
exam_tab_inactive_count = 0

multiple_faces_detected = False


for log in input_dataset:
    timestamp, face_detected, multiple_faces, window_switch, audio_detected, exam_tab_active = log

    # Rule 1: Face Not Detected (3 consecutive)
    if not face_detected:
        no_face_datected_count= no_face_datected_count + 1
        if no_face_datected_count == 3:
            risk_score = risk_score+10
            violations.append("Face not detected 3 times consecutively")
    else:
        no_face_datected_count = 0

    # Rule 2: Multiple Faces (even once)
    if multiple_faces and not multiple_faces_detected:
        risk_score = risk_score + 20
        violations.append("Multiple faces detected")
        multiple_faces_detected = True

    # Rule 3A: Window Switch > 2
    if window_switch > 2:
        risk_score = risk_score + 5
        violations.append("Window switching count > 2")

    # Rule 3B: Continuous window switching (3 logs)
    if window_switch > 0:
        window_switch_continuous = window_switch_continuous + 1
        if window_switch_continuous == 3:
            risk_score = risk_score + 10
            violations.append("Window switching suspicious pattern")
    else:
        window_switch_continuous = 0

    # Rule 4: Audio Detected
    if audio_detected:
        risk_score = risk_score + 5
        violations.append("Audio detected")

    # Rule 5: Exam Tab Inactive (2 consecutive)
    if not exam_tab_active:
        exam_tab_inactive_count = exam_tab_inactive_count + 1
        if exam_tab_inactive_count == 2:
            risk_score = risk_score + 10
            violations.append("Exam tab inactive twice consecutively")
    else:
        exam_tab_inactive_count = 0


if risk_score <= 10:
    status = "NORMAL"
elif 11 <= risk_score <= 25:
    status = "WARNING"
else:
    status = "CRITICAL"

print("Total Risk Score:", risk_score)
print("Final Status:", status)
print("Violations Found:")
for v in violations:
    print("-", v)